# Generated by Django 5.2 on 2025-04-16 00:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatars/default.jpg",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("languages_spoken", models.TextField(blank=True, null=True)),
                ("centers_of_interest", models.TextField(blank=True, null=True)),
                ("event_expectations", models.TextField(blank=True, null=True)),
                ("activity_preferences", models.TextField(blank=True, null=True)),
                (
                    "group_size_preference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dietary_restrictions", models.TextField(blank=True, null=True)),
                ("is_certified", models.BooleanField(default=False)),
                (
                    "consent_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
