# Generated by Django 5.2 on 2025-05-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofiledb",
            name="event_invitation_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="event_invitation_consent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="event_invitation_consent_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="privacy_policy_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="privacy_policy_consent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="privacy_policy_consent_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="terms_of_service_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="terms_of_service_consent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="terms_of_service_consent_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
