# Generated by Django 5.2 on 2025-05-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0002_userprofiledb_event_invitation_consent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofiledb",
            name="activity_preferences",
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="fun_fact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="music_preference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofiledb",
            name="perfect_outing_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
