# Generated by Django 5.2 on 2025-05-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0003_remove_userprofiledb_activity_preferences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofiledb",
            name="certification_selfie",
            field=models.ImageField(
                blank=True, null=True, upload_to="certification_selfies/"
            ),
        ),
    ]
