# Generated by Django 5.2 on 2025-04-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdb",
            name="activity_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="eventdb",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventdb",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventdb",
            name="time",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
