# Generated by Django 5.2 on 2025-04-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events_app", "0002_eventdb_activity_type_eventdb_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdb",
            name="image_url",
        ),
        migrations.AddField(
            model_name="eventdb",
            name="image",
            field=models.ImageField(
                blank=True,
                default="event_images/default.jpg",
                null=True,
                upload_to="event_images/",
            ),
        ),
    ]
