# Generated by Django 5.2 on 2025-05-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events_app", "0007_alter_eventdb_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdb",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
