# Generated by Django 5.2 on 2025-05-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events_app", "0008_alter_eventdb_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("is_host_message", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
